name: Download Recalls CSV

on:
  schedule:
    - cron: "0 14 * * *" # Runs every day at 10AM EST / 2PM UTC
  workflow_dispatch:      # Allows manual runs too

jobs:
  fetch-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download file
        run: |
          wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 5 -O recalls.csv https://recalls-rappels.canada.ca/sites/default/files/opendata-donneesouvertes/HCRSAMOpenData.csv

      - name: Commit and push if file changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git add recalls.csv
          git commit -m "Update recalls.csv" || echo "No changes to commit"
          git push
